plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.homa.app'
    compileSdk 36

    defaultConfig {
        applicationId 'ai.homa.app'
        minSdk 23
        targetSdk 36
        versionCode 3
        versionName "1.2"
    }

    sourceSets {
        main {
            manifest.srcFile 'app/src/main/AndroidManifest.xml'
            java.srcDirs = ['app/src/main/java']
            res.srcDirs = ['app/src/main/res']
        }
    }
}

dependencies {
}
